# Generated by Django 5.1.3 on 2024-12-17 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_rename_anio_modelo_año'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallecompra',
            old_name='Auto',
            new_name='auto',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='auto',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.auto'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos', to='clientes.modelo'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
    ]
